import { readdirSync } from 'node:fs';
import { join } from 'node:path';
import type { Lang } from '../i18n/index.ts';

/**
 * Which locale variants of a page actually exist.
 *
 * ── Why this file exists ──
 * hreflang used to be generated by swapping the language segment of the current
 * URL and keeping the rest of the path. That is correct for pages whose slug is
 * the same in every locale, and wrong for blog posts, whose slugs are translated:
 * `/en/blog/cheap-ai-tokens-total-cost-calculations/` has a real Spanish
 * translation, but it lives at `/es/blog/tokens-de-ia-baratos-costo-total/`, not
 * at `/es/blog/cheap-ai-tokens-total-cost-calculations/`. The August 2026 audit
 * HEAD-checked every alternate the site emitted: 1,511 of 3,275 returned 404,
 * and Google discards a whole hreflang cluster when the return tags do not
 * reciprocate, so the multilingual signal was worth nothing.
 *
 * Two kinds of page, two sources of truth:
 *   - blog posts  → the translation map built from Sanity (see lib/sanity.ts)
 *   - every other → the route registry below, read off the filesystem
 *
 * Both answer the same question — does the target page get generated? — and
 * neither guesses. A URL nothing will emit gets no hreflang link.
 */

export interface Alternate {
  lang: Lang;
  /** Site-root-relative path of the alternate, with a trailing slash. */
  path: string;
}

/**
 * Locale-relative paths of the static pages under `src/pages/[lang]/`, e.g.
 * `/`, `/blog/`, `/token-calculator/`.
 *
 * Read from the filesystem rather than hand-listed so a page added later is
 * covered without anybody remembering to update a constant, and a page *removed*
 * later stops being advertised. Dynamic routes (`[slug].astro`) are skipped:
 * whether one of those exists in a given locale depends on the CMS, which the
 * filesystem cannot answer.
 */
function collectRoutes(dir: string, prefix: string, out: Set<string>): void {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    // A bracketed name is a dynamic segment — the CMS decides, not the filesystem.
    if (entry.name.startsWith('[')) continue;
    if (entry.isDirectory()) {
      collectRoutes(join(dir, entry.name), `${prefix}${entry.name}/`, out);
      continue;
    }
    // Only .astro files are pages. `rss.xml.ts` is an endpoint: it is a real URL,
    // but not one a reader lands on, and it carries no hreflang.
    if (!entry.name.endsWith('.astro')) continue;
    const base = entry.name.slice(0, -'.astro'.length);
    out.add(base === 'index' ? prefix : `${prefix}${base}/`);
  }
}

/**
 * `process.cwd()` rather than a path relative to `import.meta.url`: a static
 * Astro build renders pages from a generated SSR bundle, so this module's own
 * URL at run time is not its location in the repo. Every npm script runs from
 * the project root, so cwd is.
 */
function readRouteRegistry(): ReadonlySet<string> {
  const dir = join(process.cwd(), 'src', 'pages', '[lang]');
  const routes = new Set<string>();
  try {
    collectRoutes(dir, '/', routes);
  } catch (cause) {
    throw new Error(
      `[hreflang] cannot read the localized page directory at ${dir}. ` +
      'Run the build from the project root — without this listing every page ' +
      'would silently drop its hreflang tags.',
      { cause },
    );
  }
  if (!routes.size) {
    throw new Error(`[hreflang] found no .astro pages under ${dir}.`);
  }
  return routes;
}

export const LOCALIZED_ROUTES: ReadonlySet<string> = readRouteRegistry();

/**
 * The locale-relative route key for a pathname, or `null` when the path is not a
 * static localized page — a blog post, the locale-less root, or `/404`.
 */
export function localizedRouteKey(pathname: string, lang: string): string | null {
  const prefix = `/${lang}`;
  if (pathname !== prefix && !pathname.startsWith(`${prefix}/`)) return null;
  const rest = pathname.slice(prefix.length) || '/';
  const key = rest.endsWith('/') ? rest : `${rest}/`;
  return LOCALIZED_ROUTES.has(key) ? key : null;
}

/**
 * Alternates for a static localized page. Every locale is generated for these
 * routes by `getStaticPaths`, so a route in the registry exists in all of them.
 * Returns `[]` for anything else, and an empty list emits no hreflang at all —
 * which is the right answer for `/404` and for the locale-less root.
 *
 * `langs` is passed in rather than imported: `src/i18n/index.ts` pulls in the
 * translation JSON, and keeping that out of here leaves this module loadable by
 * the test runner as well as by the bundler.
 */
export function staticPageAlternates(pathname: string, lang: string, langs: readonly Lang[]): Alternate[] {
  const key = localizedRouteKey(pathname, lang);
  if (!key) return [];
  return langs.map(l => ({ lang: l, path: `/${l}${key}` }));
}
